export const FLOW = {
  WELCOME: "WELCOME",
  ROTATE_LANDSCAPE: "ROTATE_LANDSCAPE",
  STORY_ROOM: "STORY_ROOM",
  MEMORY_BOOK: "MEMORY_BOOK",
  ROTATE_PORTRAIT: "ROTATE_PORTRAIT",
  GIFT_ROOM: "GIFT_ROOM",
  DISTANCE: "DISTANCE",
  FORGIVENESS: "FORGIVENESS",
  LETTER: "LETTER",
  FUTURE: "FUTURE",
  VOICE_MESSAGE: "VOICE_MESSAGE",
  ENDING: "ENDING",
};